#!/usr/bin/make

HDF5_INSTALL_DIR=/mnt/wrk/Frank.Willmore/usr/local/hdf5-1.9.236/

CXX=h5pcc
#CXXFLAGS=-Wall -pedantic -O2 -std=c++0x -I/mnt/wrk/Frank.Willmore/usr/local/phdf5/include
INCLUDES=$(HDF5_INSTALL_DIR)/include
CXXFLAGS=-Wall -pedantic -O2 -std=c++0x -I$(INCLUDES)
CXXDEBUGFLAGS=-Wall -pedantic -O0 -g -std=c++0x -I$(INCLUDES)

all: seism-core-slice seism-core-check

seism-core-slice: seism-core-slice.o seism-core-attributes.o
	$(CXX) $(CXXFLAGS) seism-core-attributes.o seism-core-slice.o -o $@ -lstdc++ -lh5zzfp -lzfp

check-slice: seism-core-slice seism-core-check
	mpiexec -n 8 ./seism-core-slice < ../tests/check.in
	./seism-core-check seism-test.h5
	rm seism-test.h5

seism-core.o: seism-core.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

seism-core-slice.o: seism-core-slice.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

seism-core-attributes.o: seism-core-attributes.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

seism-core-check: seism-core-check.cc seism-core-attributes.o
	$(CXX) $(CXXFLAGS) seism-core-check.cc seism-core-attributes.o -o seism-core-check -lstdc++ -lh5zzfp -lzfp

seism-core-check-debug: seism-core-check.cc seism-core-attributes.o
	$(CXX) $(CXXDEBUGFLAGS) seism-core-check.cc seism-core-attributes.o -o seism-core-check -lstdc++

clean:
	rm -f *.o *.h5

veryclean: clean
	rm -f seism-core seism-core-slice seism-core-slicexx seism-core-check

