CXX=h5pcc
CXXFLAGS=-Wall -pedantic -O2 -std=c++0x
#CXXFLAGS=-Wall -O0 -g -std=c++0x

all: seism-core-slice

seism-core: seism-core.o
	$(CXX) $(CXXFLAGS) seism-core.o -o $@ -lstdc++

seism-core-slice: seism-core-slice.o
	$(CXX) $(CXXFLAGS) seism-core-slice.o -o $@ -lstdc++

check: seism-core
#	mpiexec -n 8 ./seism-core < tests/check.in
	mpiexec -n 8 ./seism-core < tests/precreate-1.in
	mpiexec -n 8 ./seism-core < tests/precreate1.in
	mpiexec -n 8 ./seism-core < tests/precreate0.in

seism-core.o: seism-core.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

seism-core-slice.o: seism-core-slice.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f *.o *.h5

veryclean: clean
	rm -f seism-core
