#!/usr/bin/env make

#  remember to: module load cray-hdf5-parallel 
#CXX=h5pcc
CXX=CC
#CXXFLAGS=-Wall -O2  -lstdc++
CXXFLAGS=-O2 
#CXXFLAGS=-Wall -O0 -g -std=c++0x

all: seism-core

seism-core: seism-core.o
	$(CXX) $(CXXFLAGS) seism-core.o -o $@

seism-core.o: seism-core.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f *.o *.h5

veryclean: clean
	rm -f seism-core
