CXX=h5pcc
CXXFLAGS=-Wall -pedantic -O2 -std=c++0x -I/mnt/wrk/Frank.Willmore/usr/local/phdf5/include

#CXXFLAGS=-Wall -O0 -g -std=c++0x

all: seism-core-slice

seism-core: seism-core.o
	$(CXX) $(CXXFLAGS) seism-core.o -o $@ -lstdc++

seism-core-slice: seism-core-slice.o
	$(CXX) $(CXXFLAGS) seism-core-slice.o -o $@ -lstdc++

seism-core-slicexx: seism-core-slice.o
	mpicxx -Wall -std=c++0x -I/mnt/wrk/Frank.Willmore/usr/local/phdf5/include seism-core-slice.o -o seism-core-slicexx -lstdc++ -L/mnt/wrk/Frank.Willmore/usr/local/phdf5/lib -lhdf5 

check: seism-core
#	mpiexec -n 8 ./seism-core < tests/check.in
	mpiexec -n 8 ./seism-core < tests/precreate-1.in
	mpiexec -n 8 ./seism-core < tests/precreate1.in
	mpiexec -n 8 ./seism-core < tests/precreate0.in

check-slice: seism-core-slice
	mpiexec -n 8 ./seism-core-slice < tests/jelly/precreate0.in
	mpiexec -n 8 ./seism-core-slice < tests/jelly/check-8
	mpiexec -n 64 ./seism-core-slice < tests/jelly/check-64-ind

seism-core.o: seism-core.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

seism-core-slice.o: seism-core-slice.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f *.o *.h5

veryclean: clean
	rm -f seism-core
