#!/usr/bin/make

CXX=h5pcc
CXXFLAGS=-Wall -pedantic -O2 -std=c++0x -I/mnt/wrk/Frank.Willmore/usr/local/phdf5/include

#CXXFLAGS=-Wall -O0 -g -std=c++0x

all: seism-core-slice

seism-core: seism-core.o
	$(CXX) $(CXXFLAGS) seism-core.o -o $@ -lstdc++

seism-core-slice: seism-core-slice.o seism-core-attributes.o
	$(CXX) $(CXXFLAGS) seism-core-attributes.o seism-core-slice.o -o $@ -lstdc++

check-slice: seism-core-slice
	mpiexec -n 8 ./seism-core-slice < tests/jelly/check.in
#	mpiexec -n 8 ./seism-core-slice < tests/jelly/precreate0.in
#	mpiexec -n 8 ./seism-core-slice < tests/jelly/check-8-pre
#	mpiexec -n 16 ./seism-core-slice < tests/jelly/check-16-pre
#	mpiexec -n 32 ./seism-core-slice < tests/jelly/check-32-pre
#	mpiexec -n 64 ./seism-core-slice < tests/jelly/check-64-pre

seism-core.o: seism-core.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

seism-core-slice.o: seism-core-slice.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

seism-core-attributes.o: seism-core-attributes.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f *.o *.h5

veryclean: clean
	rm -f seism-core seism-core-slice seism-core-slicexx

