# Feature versions may require that certain MACROs be defined for conditional compilation
FEATURES=
include features.mk

# Platform specific stuff
CXX=h5pcc
INCLUDES=$(PHDF5_INCLUDE)
CXXFLAGS=-Wall -pedantic -O2 -lstdc++ -lh5zzfp -lzfp -std=c++0x -I$(INCLUDES) $(FEATURES)
CXXDEBUGFLAGS=-Wall -pedantic -O0 -g -std=c++0x -I$(INCLUDES) $(FEATURES)
MPI_LAUNCHER=mpiexec

include targets.mk


