#!/usr/bin/make

CXX=h5pcc
INCLUDES=$(PHDF5_INCLUDE)/include
CXXFLAGS=-Wall -pedantic -O2 -std=c++0x -I$(INCLUDES) 
CXXDEBUGFLAGS=-Wall -pedantic -O0 -g -std=c++0x -I$(INCLUDES) 

all: seism-core-slice seism-core-check

seism-core-slice: seism-core-slice.o seism-core-attributes.o
#$(CXX) $(CXXFLAGS) seism-core-attributes.o seism-core-slice.o -o $@ -lstdc++ -lh5zzfp -lzfp -ldl
	$(CXX) $(CXXFLAGS) seism-core-attributes.o seism-core-slice.o -o $@ -lstdc++ -lh5zzfp -lzfp -ldl

check-slice: seism-core-slice seism-core-check
	mpiexec -n 8 ./seism-core-slice < ../tests/check.in
	./seism-core-check seism-test.h5
	ls -l seism-test.h5
	rm seism-test.h5

check-subfile: seism-core-slice 
	mpiexec -n 8 ./seism-core-slice < ../tests/subfile.in

check-read: seism-read
	mpiexec -n 8 ./seism-read seism-test.h5

seism-read: seism-read.o seism-core-attributes.o 
	$(CXX) $(CXXFLAGS) seism-core-attributes.o seism-read.o -o $@ -lstdc++ 

check-plugin: seism-core-slice seism-core-check seism-core-plugin
	mpiexec -n 8 ./seism-core-slice < ../tests/check-plugin.in
	./seism-core-check seism-test.h5
	rm seism-test.h5

check-sd: seism-core-slice seism-core-check seism-core-plugin
	mpiexec -n 8 ./seism-core-slice < ../tests/check-sd.in
	ls -l seism-test.h5
	#./seism-core-check seism-test.h5
	rm seism-test.h5

seism-core-plugin: plugins/libplugins.so 
	cd plugins && make 

seism-core.o: seism-core.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

seism-read.o: seism-read.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

seism-core-slice.o: seism-core-slice.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

seism-core-attributes.o: seism-core-attributes.cc
	$(CXX) $(CXXFLAGS) -c $< -o $@

seism-core-check: seism-core-check.cc seism-core-attributes.o
	$(CXX) $(CXXFLAGS) seism-core-check.cc seism-core-attributes.o -o seism-core-check -lstdc++ -lh5zzfp -lzfp

seism-core-check-debug: seism-core-check.cc seism-core-attributes.o
	$(CXX) $(CXXDEBUGFLAGS) seism-core-check.cc seism-core-attributes.o -o seism-core-check -lstdc++

clean:
	rm -f *.o *.h5

veryclean: clean
	rm -f seism-core seism-core-slice seism-core-check seism-read 


