#!/bin/bash

#PBS -l nodes=192:ppn=8:xe
#PBS -l walltime=12:00:00
#PBS -N 200M-8
#PBS -m abe
#PBS -M frank.willmore@hdfgroup.org
#PBS -o $PBS_JOBNAME.out
#PBS -e $PBS_JOBNAME.err


#mkdir -p /scratch/sciteam/$USER/scale
#cd /scratch/sciteam/$USER/scale


export MPICH_MPIIO_CB_ALIGN=0
export MPICH_MPIIO_HINTS_DISPLAY=1
export CB_SIZE=33554432


function processor_geometry {

grep "^$1" << EOF | awk '{print $2}' | sed -e "s/:/ /g" 
8 2:2:2
16 2:2:4
24 2:3:4
36 3:3:4
48 3:4:4
64 4:4:4
96 4:4:6
384 6:8:8
768 8:8:12
1536 8:12:16
3072 12:16:16
EOF

}


SEISM_CORE=/u/sciteam/willmore/seism-core/seism-core
TIME_STEPS=2

printf "no time, no collective\n"
for config in "8 96" "8 384" "8 768" "8 1536" 
do

ppn=`echo $config | awk '{print $1}'`
processors=`echo $config | awk '{print $2}'`
p_geom=`processor_geometry $processors` 
export MPICH_MPIIO_HINTS="*:cb_nodes=$processors:cb_buffer_size=$CB_SIZE"


tput=`aprun -N$ppn -n$processors $SEISM_CORE << EOF | grep throughput | awk '{print $3}' 
processor $p_geom
chunk 320 320 512
domain 320 320 512
time $TIME_STEPS
#use_collective
#separate_timesteps
DONE
EOF`

printf "%d\t%g\n" $processors $tput
done #done with this processor configuration

#==========
date
#==========

printf "time, no collective\n"
for config in "8 96" "8 384" "8 768" "8 1536" 
do

ppn=`echo $config | awk '{print $1}'`
processors=`echo $config | awk '{print $2}'`
p_geom=`processor_geometry $processors` 
export MPICH_MPIIO_HINTS="*:cb_nodes=$processors:cb_buffer_size=$CB_SIZE"

tput=`aprun -N$ppn -n$processors $SEISM_CORE << EOF | grep throughput | awk '{print $3}' 
processor $p_geom
chunk 320 320 512
domain 320 320 512
time $TIME_STEPS
#use_collective
separate_timesteps
DONE
EOF`

printf "%d\t%g\n" $processors $tput
done #done with this processor configuration

#==========
date
#==========

printf "no time, collective\n"
for config in "8 96" "8 384" "8 768" "8 1536" 
do

ppn=`echo $config | awk '{print $1}'`
processors=`echo $config | awk '{print $2}'`
p_geom=`processor_geometry $processors` 
export MPICH_MPIIO_HINTS="*:cb_nodes=$processors:cb_buffer_size=$CB_SIZE"

tput=`aprun -N$ppn -n$processors $SEISM_CORE << EOF | grep throughput | awk '{print $3}' 
processor $p_geom
chunk 320 320 512
domain 320 320 512
time $TIME_STEPS
use_collective
#separate_timesteps
DONE
EOF`

printf "%d\t%g\n" $processors $tput
done #done with this processor configuration

#==========
date
#==========

printf "time, collective\n"
for config in "8 96" "8 384" "8 768" "8 1536" 
do

ppn=`echo $config | awk '{print $1}'`
processors=`echo $config | awk '{print $2}'`
p_geom=`processor_geometry $processors` 
export MPICH_MPIIO_HINTS="*:cb_nodes=$processors:cb_buffer_size=$CB_SIZE"

tput=`aprun -N$ppn -n$processors $SEISM_CORE << EOF | grep throughput | awk '{print $3}' 
processor $p_geom
chunk 320 320 512
domain 320 320 512
time $TIME_STEPS
use_collective
separate_timesteps
DONE
EOF`

printf "%d\t%g\n" $processors $tput
done #done with this processor configuration

#==========
date
#==========
