# Feature versions may require that certain MACROs be defined for conditional compilation
FEATURES=
include features.mk

#PHDF5_INCLUDE=$(WORK)/usr/local/phdf5/include
PHDF5_INCLUDE=/lfs/software/opt/linux-rocky8-x86_64/gcc-12.1.0/hdf5-1.12.2-e7j3xrg5imwffjidgcvt3nzdrleaqq6d/include

# Platform specific stuff
CXX=h5pcc
INCLUDES=$(PHDF5_INCLUDE)
CXXFLAGS=-Wall -pedantic -O2 -lstdc++ $(ZFP_FLAGS) -std=c++0x -I$(INCLUDES) $(FEATURES)
CXXDEBUGFLAGS=-Wall -pedantic -O0 -g -std=c++0x -I$(INCLUDES) $(FEATURES)

#MPI_LAUNCHER=ibrun -o 0 
MPI_LAUNCHER=mpirun

include targets.mk


